### ISSUE TITLE
cds-services not registering after commit b977daae5895e6f6c2fd89726284aab71e0a48c3

### ISSUE THREAD

**Issue by mattStorer** [DBCG/cqf-ruler#575] opened 2022-07-27 17:10 UTC
we've been using cqf-ruler on the master branch.  we load FHIR resources into cqf-ruler that drive CDS Service operations.  however, something recently broke this functionality.

I tracked the problem down to commit b977daae5895e6f6c2fd89726284aab71e0a48c3 ("Fixed CDS Hooks service cache"), which appears to have something in it that breaks this functionality, insofar as after loading appropriate resources into CQF Ruler, this action no longer triggers the creation or representation of the associated CDS Services that are supposed to get created (i.e., "curl http://localhost:8080/cds-services" returns an empty array).

A commit from the previous day, f4c78a394482e8750ed15499e8ca6b0f9893b14b ("Fix bug in searching by version") restores the needed functionality, so we will be staying on this commit for our operations until this ticket is resolved.

Please let me know if you have any questions about any of the above.

Thanks!

**Comment by mattStorer** [comment] 2022-07-27 20:31
> A commit from the previous day, https://github.com/DBCG/cqf-ruler/commit/f4c78a394482e8750ed15499e8ca6b0f9893b14b ("Fix bug in searching by version") restores the needed functionality, so we will be staying on this commit for our operations until this ticket is resolved.

Now that I think about it, this strategy is not going to be viable except in the very short term, as this build relies on SNAPSHOT dependencies, and over time these dependencies will cease to be compatible with this build of the ruler, which will likely force use to revert back to 0.4.1.

Eagerly awaiting the next tagged stable release -

**Comment by c-schuler** [comment] 2022-07-27 21:14
Hi @mattStorer! I just tested this locally by posting an artifact bundle with a PlanDefinition resource. It is updating the cache as expected and returning the service when calling the discovery endpoint. Note that the cache will remove services when the corresponding PlanDefinition is deleted. Would you mind sharing your artifact bundle or PlanDefinition so I can repro?

**Comment by c-schuler** [comment] 2022-07-29 20:59
The issue is that the cache is cleared when restarting the server, requiring a clean build and re-upload of resources.

**Comment by c-schuler** [comment] 2022-08-02 15:22
@mattStorer please verify that PR #578 resolved this issue.

**Comment by aeyates** [comment] 2022-08-03 00:06
@c-schuler and @mattStorer I pulled down the latest and confirmed that services now survive a restart without having to clean, package, and push resources again. Thanks!

**Comment by c-schuler** [comment] 2022-08-03 20:28
Thank you @aeyates !
Closing this

**Closed by c-schuler** 2022-08-03 20:28 UTC
Labels: bug, cds-hooks
