### ISSUE TITLE
$validate is not working

### ISSUE THREAD

**Issue by p9g** [DBCG/cqf-ruler#510] opened 2022-05-05 13:52 UTC
$validate does not work.
For example, 
https://cloud.alphora.com/sandbox/r4/cqm/fhir/Library/SafeUseofOpioidsConcurrentPrescribingFHIR/$validate
returns
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": ...
  },
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Failed to call access method: java.lang.AbstractMethodError: Receiver class org.hl7.fhir.common.hapi.validation.validator.FhirInstanceValidator$NullEvaluationContext does not define or inherit an implementation of the resolved method 'abstract java.util.List resolveConstant(java.lang.Object, java.lang.String, boolean)' of interface org.hl7.fhir.r5.utils.FHIRPathEngine$IEvaluationContext."
    }
  ]
}

This prevents tools like http://gb2.clinfhir.com/ from saving to a CQF Ruler because that tool tries to do $validate before saving

**Comment by JPercival** [comment] 2022-06-07 14:32
This is caused by a mismatch between the fhir core versions and the hapi versions referenced by the cqf-ruler. It's fixed on `master`, I need to redeploy the sandboxes so they pick up the fix.

**Comment by c-schuler** [comment] 2022-07-22 20:20
The $validate operation is now functioning as intended.

**Closed by c-schuler** 2022-07-22 20:20 UTC
Labels: bug
